all: binarytrees.gpp-5.gpp_run

binarytrees.gpp-5.gpp_run: binarytrees.gpp-5.c++
	/usr/bin/g++ -c -pipe -O3 -fomit-frame-pointer -march=ivybridge -std=gnu++17 binarytrees.gpp-5.c++ -o binarytrees.gpp-5.c++.o
	/usr/bin/g++ binarytrees.gpp-5.c++.o -o binarytrees.gpp-5.gpp_run -lpthread